name: test_&_linter_check

on: push

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run linter
        run: make test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          LOCALE: ${{ secrets.LOCALE }}
      - name: Publish code coverage report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true